trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
          - script: npm install
          - script: npm run build -- --prod
          - publish: dist
            artifact: dist

  - stage: deploy_dev
    displayName: Deploy to development
    jobs:
    - deployment: DeployPWA
      environment: DEV
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Hello, development world!

  - stage: deploy_prd
    displayName: Deploy to production
    jobs:
    - deployment: DeployPWA
      environment: PRD
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Hello, production world!